eureka:
  client:
    service-url:
      defaultZone: http://registry.kimloong.me:8761/eureka/

security:
  oauth2:
    client:
      access-token-uri: http://uaa.kimloong.me:5000/oauth/token
      grant-type: client_credentials
    resource:
      token-info-uri: http://uaa.kimloong.me:5000/oauth/check_token

logging:
  level:
    spring.framework: debug